apiVersion: v1
kind: Namespace
metadata:
  name: price-fetcher-staging
  labels:
    name: price-fetcher-staging

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-fetcher-deployment
  namespace: price-fetcher-staging
  labels:
    app: price-fetcher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-fetcher-deployment
  template:
    metadata:
      labels:
        app: price-fetcher-deployment
    spec:
      containers:
      - name: price-fetcher
        image: price-fetcher
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: fetcher-port
        envFrom:
          - secretRef:
              name: price-fetcher-environment
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: price-fetcher-service
  namespace: price-fetcher-staging
spec:
  selector:
    app: price-fetcher-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: fetcher-port
  type: LoadBalancer